(()=>{
'use strict';
let recRows=[],spotRows=[],editingSpotId=null,adoptingRecId=null;
const q=s=>document.querySelector(s);
const safe=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const statusLabel=s=>({pending:'確認待ち',approved:'採用済み',rejected:'見送り'}[s]||s);
const norm=s=>String(s||'').normalize('NFKC').trim().toLowerCase().replace(/[\s　]+/g,'');
const validUrl=s=>{if(!s)return true;try{const u=new URL(s);return u.protocol==='https:'||u.protocol==='http:'}catch{return false}};

function enhanceLogin(){const login=q('#adminLogin');if(!login||q('#resetPasswordBtn'))return;const form=q('#loginForm');const btn=document.createElement('button');btn.type='button';btn.id='resetPasswordBtn';btn.className='btn soft';btn.textContent='パスワードを忘れた方';form.appendChild(btn);const box=document.createElement('div');box.id='passwordRecoveryBox';box.className='hidden';box.innerHTML='<div class="note" style="margin-top:12px">登録メールアドレスにパスワード再設定メールを送ります。</div><div class="formgrid" style="margin-top:10px"><input id="resetEmail" type="email" placeholder="登録メールアドレス"><button id="sendResetBtn" class="btn primary" type="button">再設定メールを送る</button></div><div id="resetMsg" class="formmsg"></div>';login.appendChild(box);btn.onclick=()=>{box.classList.toggle('hidden');q('#resetEmail').value=form.elements.email?.value||''};q('#sendResetBtn').onclick=sendReset}
async function sendReset(){const email=q('#resetEmail').value.trim(),msg=q('#resetMsg'),btn=q('#sendResetBtn');if(!email){msg.textContent='メールアドレスを入力してください。';return}btn.disabled=true;msg.textContent='送信中…';const {error}=await db.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});btn.disabled=false;msg.textContent=error?'送信できませんでした：'+error.message:'再設定メールを送りました。メール内のリンクを開いてください。'}
function showNewPassword(){if(q('#newPasswordOverlay'))return;const wrap=document.createElement('div');wrap.id='newPasswordOverlay';wrap.style='position:fixed;inset:0;background:rgba(45,34,28,.55);z-index:100;display:grid;place-items:center;padding:18px';wrap.innerHTML='<div class="formcard" style="width:min(520px,100%)"><h2 style="margin-top:0">新しいパスワードを設定</h2><div class="sub" style="margin-bottom:12px">8文字以上の新しい管理者パスワードを入力してください。</div><div class="formgrid"><input id="newPassword" type="password" minlength="8" autocomplete="new-password" placeholder="新しいパスワード"><input id="newPassword2" type="password" minlength="8" autocomplete="new-password" placeholder="もう一度入力"><button id="saveNewPassword" class="btn primary" type="button">新しいパスワードを保存</button></div><div id="newPasswordMsg" class="formmsg"></div></div>';document.body.appendChild(wrap);q('#saveNewPassword').onclick=saveNewPassword}
async function saveNewPassword(){const a=q('#newPassword').value,b=q('#newPassword2').value,msg=q('#newPasswordMsg'),btn=q('#saveNewPassword');if(a.length<8){msg.textContent='8文字以上で設定してください。';return}if(a!==b){msg.textContent='2つのパスワードが一致しません。';return}btn.disabled=true;msg.textContent='保存中…';const {error}=await db.auth.updateUser({password:a});btn.disabled=false;if(error){msg.textContent='変更できませんでした：'+error.message;return}msg.textContent='パスワードを変更しました。管理者ページを開きます。';setTimeout(()=>{q('#newPasswordOverlay')?.remove();history.replaceState(null,'',location.pathname+location.search);showAdmin()},700)}
function isRecoveryLink(){const h=new URLSearchParams((location.hash||'').replace(/^#/,''));const s=new URLSearchParams(location.search);return h.get('type')==='recovery'||s.get('type')==='recovery'||h.has('code')&&h.get('type')==='recovery'}
function setupRecovery(){enhanceLogin();const recovery=isRecoveryLink();if(!recovery){q('#newPasswordOverlay')?.remove();return}db.auth.onAuthStateChange(event=>{if(event==='PASSWORD_RECOVERY')showNewPassword()});setTimeout(showNewPassword,250)}

function enhanceSpotForm(){const form=q('#spotForm');if(!form||form.dataset.enhanced)return;form.dataset.enhanced='1';const map=form.querySelector('[name="map_url"]');const images=document.createElement('textarea');images.name='image_urls';images.placeholder='画像URL（複数の場合は改行またはカンマ区切り）';images.style.minHeight='78px';map.after(images);const submit=form.querySelector('button[type="submit"]');submit.id='spotSubmitBtn';const cancel=document.createElement('button');cancel.type='button';cancel.id='cancelEditSpot';cancel.className='btn soft hidden';cancel.textContent='編集をキャンセル';submit.after(cancel);cancel.onclick=resetSpotForm;form.addEventListener('submit',saveSpot,true)}
function resetSpotForm(){const form=q('#spotForm');if(!form)return;form.reset();form.elements.is_published.checked=true;editingSpotId=null;adoptingRecId=null;q('#spotSubmitBtn').textContent='スポットを登録';q('#cancelEditSpot').classList.add('hidden');q('#spotMsg').textContent=''}
function parseImages(v){return String(v||'').split(/[\n,]+/).map(x=>x.trim()).filter(Boolean)}
async function saveSpot(e){e.preventDefault();e.stopImmediatePropagation();const form=e.currentTarget,msg=q('#spotMsg'),btn=q('#spotSubmitBtn');const f=new FormData(form);const name=String(f.get('name')||'').trim(),municipality=String(f.get('municipality')||'').trim();if(!name||!municipality){msg.textContent='スポット名と市町村は必須です。';return}const urls=['website_url','instagram_url','post_url','map_url'].map(k=>String(f.get(k)||'').trim()).filter(Boolean);const images=parseImages(f.get('image_urls'));if([...urls,...images].some(x=>!validUrl(x))){msg.textContent='URLの形式を確認してください。http:// または https:// から入力してください。';return}const dup=spotRows.find(x=>x.id!==editingSpotId&&norm(x.name)===norm(name)&&norm(x.municipality)===norm(municipality));if(dup&&!confirm('同じ市町村に「'+dup.name+'」が登録されています。重複の可能性がありますが保存しますか？'))return;btn.disabled=true;msg.textContent=editingSpotId?'更新中…':'登録中…';const payload={name,municipality,category:String(f.get('category')||'').trim(),description:String(f.get('description')||'').trim(),website_url:String(f.get('website_url')||'').trim()||null,instagram_url:String(f.get('instagram_url')||'').trim()||null,post_url:String(f.get('post_url')||'').trim()||null,map_url:String(f.get('map_url')||'').trim()||null,image_urls:images,is_published:f.get('is_published')==='on',updated_at:new Date().toISOString()};const res=editingSpotId?await db.from('seiban_spots').update(payload).eq('id',editingSpotId):await db.from('seiban_spots').insert(payload);if(res.error){msg.textContent='保存できませんでした：'+res.error.message;btn.disabled=false;return}if(adoptingRecId){const ar=await db.from('seiban_recommendations').update({status:'approved'}).eq('id',adoptingRecId);if(ar.error)console.warn(ar.error)}msg.textContent=editingSpotId?'更新しました。':'登録しました。';btn.disabled=false;editingSpotId=null;adoptingRecId=null;form.reset();form.elements.is_published.checked=true;btn.textContent='スポットを登録';q('#cancelEditSpot').classList.add('hidden');await loadRemoteSpots();await loadAdmin()}
window.adoptRecommendation=function(id){const r=recRows.find(x=>x.id===id);if(!r)return;enhanceSpotForm();const duplicate=spotRows.find(x=>norm(x.name)===norm(r.spot_name)&&norm(x.municipality)===norm(r.municipality));if(duplicate&&!confirm('「'+duplicate.name+'」はすでに登録されています。内容を確認して進みますか？'))return;const f=q('#spotForm');editingSpotId=null;adoptingRecId=id;f.elements.name.value=r.spot_name||'';f.elements.municipality.value=r.municipality||'';f.elements.category.value=r.category||'おすすめ';f.elements.description.value=r.recommendation||'';if(r.url){if(/instagram\.com/i.test(r.url))f.elements.instagram_url.value=r.url;else f.elements.website_url.value=r.url}f.elements.is_published.checked=false;q('#spotSubmitBtn').textContent='内容を確認して登録';q('#cancelEditSpot').classList.remove('hidden');q('#spotMsg').textContent='おすすめ内容を引き継ぎました。確認後に登録すると、この投稿は自動で「採用済み」になります。';f.scrollIntoView({behavior:'smooth',block:'start'})};
window.editSpot=function(id){const r=spotRows.find(x=>x.id===id);if(!r)return;enhanceSpotForm();const f=q('#spotForm');editingSpotId=id;adoptingRecId=null;['name','municipality','category','description','website_url','instagram_url','post_url','map_url'].forEach(k=>{if(f.elements[k])f.elements[k].value=r[k]||''});f.elements.image_urls.value=(r.image_urls||[]).join('\n');f.elements.is_published.checked=!!r.is_published;q('#spotSubmitBtn').textContent='変更を保存';q('#cancelEditSpot').classList.remove('hidden');q('#spotMsg').textContent='編集中：'+r.name;f.scrollIntoView({behavior:'smooth',block:'start'})};
window.setRecStatus=async function(id,status){if(status==='rejected'&&!confirm('このおすすめを見送りにしますか？'))return;const {error}=await db.from('seiban_recommendations').update({status}).eq('id',id);if(error)return alert('更新できませんでした：'+error.message);await loadAdmin()};

function enhanceAdminUI(){const rl=q('#recommendList');if(!rl||q('#adminModerationTools'))return;const tools=document.createElement('div');tools.id='adminModerationTools';tools.style='display:grid;gap:10px;margin:10px 0 14px';tools.innerHTML='<input id="adminRecSearch" type="search" placeholder="おすすめを検索（店名・市町村・内容）"><div id="adminSummary" class="small"></div>';rl.before(tools);q('#adminRecSearch').addEventListener('input',renderAdminLists)}
function duplicateInfo(r){const s=spotRows.find(x=>norm(x.name)===norm(r.spot_name)&&norm(x.municipality)===norm(r.municipality));if(s)return '登録済みスポットと重複の可能性';const same=recRows.filter(x=>x.id!==r.id&&norm(x.spot_name)===norm(r.spot_name)&&norm(x.municipality)===norm(r.municipality));return same.length?'おすすめ内に同名投稿あり':''}
function renderAdminLists(){const rl=q('#recommendList'),sl=q('#adminSpotList');if(!rl||!sl)return;const term=norm(q('#adminRecSearch')?.value||'');const filtered=recRows.filter(r=>!term||norm([r.spot_name,r.municipality,r.category,r.recommendation,r.nickname].join(' ')).includes(term));const pending=filtered.filter(r=>r.status==='pending'),done=filtered.filter(r=>r.status!=='pending');const sum=q('#adminSummary');if(sum)sum.textContent=`確認待ち ${recRows.filter(r=>r.status==='pending').length}件 ／ 採用済み ${recRows.filter(r=>r.status==='approved').length}件 ／ 見送り ${recRows.filter(r=>r.status==='rejected').length}件`;
 const renderRec=r=>{const dup=duplicateInfo(r);return `<div class="adminitem"><b>${safe(r.spot_name)}</b><div class="small">${safe(r.municipality)}${r.category?' · '+safe(r.category):''} · ${statusLabel(r.status)}</div>${dup?`<div class="small" style="margin-top:6px;font-weight:700">⚠ ${safe(dup)}</div>`:''}<div style="margin-top:7px;font-size:13px;line-height:1.6">${safe(r.recommendation)}</div>${r.nickname?`<div class="small">投稿者：${safe(r.nickname)}</div>`:''}${r.url?`<a href="${safe(r.url)}" target="_blank" rel="noopener noreferrer" class="small">参考URLを開く ↗</a>`:''}<div class="adminbar">${r.status==='pending'?`<button class="btn primary" onclick="adoptRecommendation(${r.id})">採用して編集</button><button class="btn danger" onclick="setRecStatus(${r.id},'rejected')">見送り</button>`:`<button class="btn soft" onclick="setRecStatus(${r.id},'pending')">確認待ちに戻す</button>`}</div></div>`};rl.innerHTML=(pending.length?`<div class="small">表示中の確認待ち ${pending.length}件</div>`+pending.map(renderRec).join(''):'<div class="small">該当する確認待ちはありません。</div>')+(done.length?`<details style="margin-top:12px"><summary class="small">処理済み ${done.length}件</summary>${done.map(renderRec).join('')}</details>`:'');sl.innerHTML=spotRows.length?spotRows.map(r=>`<div class="adminitem"><b>${safe(r.name)}</b><div class="small">${safe(r.municipality)} · ${safe(r.category)} · ${r.is_published?'公開中':'下書き'}</div><div class="adminbar"><button class="btn soft" onclick="editSpot(${r.id})">編集</button><button class="btn soft" onclick="togglePublish(${r.id},${!r.is_published})">${r.is_published?'非公開にする':'公開する'}</button><button class="btn danger" onclick="deleteSpot(${r.id})">削除</button></div></div>`).join(''):'<div class="small">管理画面から追加したスポットはまだありません。</div>'}
window.loadAdmin=async function(){enhanceSpotForm();enhanceAdminUI();const rl=q('#recommendList'),sl=q('#adminSpotList');if(!rl||!sl)return;rl.innerHTML='<div class="small">読み込み中…</div>';sl.innerHTML='<div class="small">読み込み中…</div>';const [rr,ss]=await Promise.all([db.from('seiban_recommendations').select('*').order('created_at',{ascending:false}),db.from('seiban_spots').select('*').order('created_at',{ascending:false})]);if(rr.error){rl.innerHTML='<div class="note">おすすめ一覧を読み込めません：'+safe(rr.error.message)+'</div>';return}if(ss.error){sl.innerHTML='<div class="note">スポット一覧を読み込めません：'+safe(ss.error.message)+'</div>';return}recRows=rr.data||[];spotRows=ss.data||[];renderAdminLists()};

const publicForm=q('#recommendForm');if(publicForm){let lastSubmit=0;publicForm.addEventListener('submit',async e=>{e.preventDefault();e.stopImmediatePropagation();const msg=q('#recommendMsg'),btn=publicForm.querySelector('button[type="submit"]');const now=Date.now();if(btn.disabled)return;if(now-lastSubmit<15000){msg.textContent='連続送信は少し時間をあけてください。';return}const f=new FormData(publicForm),name=String(f.get('spot_name')||'').trim(),municipality=String(f.get('municipality')||'').trim(),recommendation=String(f.get('recommendation')||'').trim(),url=String(f.get('url')||'').trim();if(name.length<2||recommendation.length<2){msg.textContent='スポット名とおすすめ理由をもう少し詳しく入力してください。';return}if(name.length>120||recommendation.length>1000){msg.textContent='入力が長すぎます。内容を少し短くしてください。';return}if(url&&!validUrl(url)){msg.textContent='参考URLの形式を確認してください。';return}btn.disabled=true;btn.textContent='送信中…';msg.textContent='送信中…';const payload={spot_name:name,municipality,category:String(f.get('category')||'').trim()||null,recommendation,url:url||null,nickname:String(f.get('nickname')||'').trim().slice(0,80)||null,status:'pending'};try{const {data:recent}=await db.from('seiban_recommendations').select('id,spot_name,municipality,created_at').eq('spot_name',name).eq('municipality',municipality).gte('created_at',new Date(Date.now()-86400000).toISOString()).limit(1);if(recent?.length){msg.textContent='同じスポットのおすすめが最近届いています。内容を確認してから再度お試しください。';btn.disabled=false;btn.textContent='おすすめを送る';return}const {error}=await db.from('seiban_recommendations').insert(payload);if(error)throw error;lastSubmit=Date.now();publicForm.reset();msg.textContent='ありがとう！おすすめ情報を受け付けました。管理者が内容を確認します。';btn.textContent='送信しました';setTimeout(()=>{btn.disabled=false;btn.textContent='おすすめを送る'},2500)}catch(err){msg.textContent='送信エラー：'+(err.message||'通信に失敗しました');btn.disabled=false;btn.textContent='おすすめを送る'}},true)}
enhanceSpotForm();setupRecovery();
})();