(()=>{
'use strict';
let recRows=[],spotRows=[],editingSpotId=null,adoptingRecId=null,recFilter='pending';
const q=s=>document.querySelector(s);
const safe=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const norm=s=>String(s||'').normalize('NFKC').trim().toLowerCase().replace(/[\s　]+/g,'');
const validUrl=s=>{if(!s)return true;try{const u=new URL(s);return ['http:','https:'].includes(u.protocol)}catch{return false}};
const statusLabel=s=>({pending:'確認待ち',approved:'採用済み',rejected:'見送り'}[s]||s);

function enhanceLogin(){const login=q('#adminLogin'),form=q('#loginForm');if(!login||!form||q('#resetPasswordBtn'))return;const btn=document.createElement('button');btn.type='button';btn.id='resetPasswordBtn';btn.className='btn soft';btn.textContent='パスワードを忘れた方';form.appendChild(btn);const box=document.createElement('div');box.id='passwordRecoveryBox';box.className='hidden';box.innerHTML='<div class="note" style="margin-top:12px">登録メールアドレスにパスワード再設定メールを送ります。</div><div class="formgrid" style="margin-top:10px"><input id="resetEmail" type="email" placeholder="登録メールアドレス"><button id="sendResetBtn" class="btn primary" type="button">再設定メールを送る</button></div><div id="resetMsg" class="formmsg"></div>';login.appendChild(box);btn.onclick=()=>{box.classList.toggle('hidden');q('#resetEmail').value=form.elements.email?.value||''};q('#sendResetBtn').onclick=async()=>{const email=q('#resetEmail').value.trim(),msg=q('#resetMsg');if(!email)return msg.textContent='メールアドレスを入力してください。';const {error}=await db.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});msg.textContent=error?'送信できませんでした：'+error.message:'再設定メールを送りました。'}}
function isRecoveryLink(){const h=new URLSearchParams((location.hash||'').replace(/^#/,'')),s=new URLSearchParams(location.search);return h.get('type')==='recovery'||s.get('type')==='recovery'}
function showNewPassword(){if(q('#newPasswordOverlay'))return;const w=document.createElement('div');w.id='newPasswordOverlay';w.style='position:fixed;inset:0;background:rgba(45,34,28,.55);z-index:100;display:grid;place-items:center;padding:18px';w.innerHTML='<div class="formcard" style="width:min(520px,100%)"><h2>新しいパスワードを設定</h2><div class="formgrid"><input id="newPassword" type="password" minlength="8" placeholder="新しいパスワード"><input id="newPassword2" type="password" minlength="8" placeholder="もう一度入力"><button id="saveNewPassword" class="btn primary" type="button">新しいパスワードを保存</button></div><div id="newPasswordMsg" class="formmsg"></div></div>';document.body.appendChild(w);q('#saveNewPassword').onclick=async()=>{const a=q('#newPassword').value,b=q('#newPassword2').value,msg=q('#newPasswordMsg');if(a.length<8)return msg.textContent='8文字以上で設定してください。';if(a!==b)return msg.textContent='2つのパスワードが一致しません。';const {error}=await db.auth.updateUser({password:a});if(error)return msg.textContent='変更できませんでした：'+error.message;w.remove();history.replaceState(null,'',location.pathname+location.search);if(typeof showAdmin==='function')showAdmin()}}
function setupRecovery(){enhanceLogin();if(isRecoveryLink()){db.auth.onAuthStateChange(e=>{if(e==='PASSWORD_RECOVERY')showNewPassword()});setTimeout(showNewPassword,250)}}

function enhanceSpotForm(){const f=q('#spotForm');if(!f||f.dataset.enhanced)return;f.dataset.enhanced='1';if(!f.elements.image_urls){const map=f.querySelector('[name="map_url"]'),t=document.createElement('textarea');t.name='image_urls';t.placeholder='画像URL（複数の場合は改行またはカンマ区切り）';t.style.minHeight='78px';map?.after(t)}const submit=f.querySelector('button[type="submit"]');if(submit)submit.id='spotSubmitBtn';if(!q('#cancelEditSpot')){const c=document.createElement('button');c.type='button';c.id='cancelEditSpot';c.className='btn soft hidden';c.textContent='編集をキャンセル';submit?.after(c);c.onclick=resetSpotForm}f.addEventListener('submit',saveSpot,true)}
function resetSpotForm(){const f=q('#spotForm');if(!f)return;f.reset();if(f.elements.is_published)f.elements.is_published.checked=true;editingSpotId=adoptingRecId=null;if(q('#spotSubmitBtn'))q('#spotSubmitBtn').textContent='スポットを登録';q('#cancelEditSpot')?.classList.add('hidden');if(q('#spotMsg'))q('#spotMsg').textContent=''}
const parseImages=v=>String(v||'').split(/[\n,]+/).map(x=>x.trim()).filter(Boolean);
async function saveSpot(e){e.preventDefault();e.stopImmediatePropagation();const f=e.currentTarget,msg=q('#spotMsg'),btn=q('#spotSubmitBtn'),fd=new FormData(f),name=String(fd.get('name')||'').trim(),municipality=String(fd.get('municipality')||'').trim();if(!name||!municipality)return msg.textContent='スポット名と市町村は必須です。';const images=parseImages(fd.get('image_urls'));const urls=['website_url','instagram_url','post_url','map_url'].map(k=>String(fd.get(k)||'').trim()).filter(Boolean);if([...urls,...images].some(x=>!validUrl(x)))return msg.textContent='URLの形式を確認してください。';const payload={name,municipality,category:String(fd.get('category')||'').trim(),description:String(fd.get('description')||'').trim(),website_url:String(fd.get('website_url')||'').trim()||null,instagram_url:String(fd.get('instagram_url')||'').trim()||null,post_url:String(fd.get('post_url')||'').trim()||null,map_url:String(fd.get('map_url')||'').trim()||null,image_urls:images,is_published:fd.get('is_published')==='on',updated_at:new Date().toISOString()};btn.disabled=true;const res=editingSpotId?await db.from('seiban_spots').update(payload).eq('id',editingSpotId):await db.from('seiban_spots').insert(payload);btn.disabled=false;if(res.error)return msg.textContent='保存できませんでした：'+res.error.message;if(adoptingRecId)await db.from('seiban_recommendations').update({status:'approved'}).eq('id',adoptingRecId);msg.textContent=editingSpotId?'更新しました。':'登録しました。';resetSpotForm();if(typeof loadRemoteSpots==='function')await loadRemoteSpots();await window.loadAdmin()}
window.editSpot=id=>{const r=spotRows.find(x=>String(x.id)===String(id));if(!r)return;enhanceSpotForm();const f=q('#spotForm');editingSpotId=id;adoptingRecId=null;['name','municipality','category','description','website_url','instagram_url','post_url','map_url'].forEach(k=>{if(f.elements[k])f.elements[k].value=r[k]||''});if(f.elements.image_urls)f.elements.image_urls.value=(r.image_urls||[]).join('\n');f.elements.is_published.checked=!!r.is_published;q('#spotSubmitBtn').textContent='変更を保存';q('#cancelEditSpot')?.classList.remove('hidden');q('#spotMsg').textContent='編集中：'+r.name;f.scrollIntoView({behavior:'smooth',block:'start'})};
window.adoptRecommendation=id=>{const r=recRows.find(x=>String(x.id)===String(id));if(!r)return;enhanceSpotForm();const f=q('#spotForm');editingSpotId=null;adoptingRecId=id;f.elements.name.value=r.spot_name||'';f.elements.municipality.value=r.municipality||'';f.elements.category.value=r.category||'おすすめ';f.elements.description.value=r.recommendation||'';if(r.url){if(/instagram\.com/i.test(r.url))f.elements.instagram_url.value=r.url;else f.elements.website_url.value=r.url}f.elements.is_published.checked=false;q('#spotSubmitBtn').textContent='内容を確認して登録';q('#cancelEditSpot')?.classList.remove('hidden');q('#spotMsg').textContent='おすすめ内容を引き継ぎました。登録すると「採用済み」になります。';f.scrollIntoView({behavior:'smooth',block:'start'})};

window.togglePublish=async(id,next)=>{const r=spotRows.find(x=>String(x.id)===String(id)),label=next?'公開':'非公開';if(!r)return alert('対象スポットが見つかりません。再読み込みしてください。');if(!next&&!confirm('「'+r.name+'」を非公開にしますか？\n一般ページからは表示されなくなります。'))return;const {data,error}=await db.from('seiban_spots').update({is_published:!!next,updated_at:new Date().toISOString()}).eq('id',id).select('id,is_published');if(error)return alert(label+'にできませんでした：'+error.message);if(!data?.length)return alert(label+'にできませんでした。Supabaseの更新権限（RLS）を確認してください。');r.is_published=!!next;renderAdminLists();if(typeof loadRemoteSpots==='function')await loadRemoteSpots();alert(next?'公開しました。':'非公開にしました。')};
window.deleteSpot=async id=>{const r=spotRows.find(x=>String(x.id)===String(id));if(!r||!confirm('「'+r.name+'」を削除しますか？\nこの操作は元に戻せません。'))return;const {error}=await db.from('seiban_spots').delete().eq('id',id);if(error)return alert('削除できませんでした：'+error.message);if(typeof loadRemoteSpots==='function')await loadRemoteSpots();await window.loadAdmin()};
window.setRecStatus=async(id,status)=>{if(status==='rejected'&&!confirm('このおすすめを見送りにしますか？'))return;const {data,error}=await db.from('seiban_recommendations').update({status}).eq('id',id).select('id,status');if(error)return alert('更新できませんでした：'+error.message);if(!data?.length)return alert('更新できませんでした。Supabaseの更新権限（RLS）を確認してください。');await window.loadAdmin()};

function enhanceAdminUI(){const rl=q('#recommendList');if(!rl)return;let tools=q('#adminModerationTools');if(!tools){tools=document.createElement('div');tools.id='adminModerationTools';tools.style='display:grid;gap:10px;margin:10px 0 14px';tools.innerHTML='<input id="adminRecSearch" type="search" placeholder="おすすめを検索（店名・市町村・内容）"><div id="adminSummary" class="small"></div><div id="adminRecTabs" class="adminbar"></div>';rl.before(tools);q('#adminRecSearch').addEventListener('input',renderAdminLists)}renderTabs()}
function renderTabs(){const box=q('#adminRecTabs');if(!box)return;const items=[['pending','確認待ち'],['approved','採用済み'],['rejected','見送り'],['all','すべて']];box.innerHTML=items.map(([v,l])=>`<button type="button" class="btn ${recFilter===v?'primary':'soft'}" data-rec-filter="${v}">${l}</button>`).join('');box.querySelectorAll('[data-rec-filter]').forEach(b=>b.onclick=()=>{recFilter=b.dataset.recFilter;renderTabs();renderAdminLists()})}
function duplicateInfo(r){const s=spotRows.find(x=>norm(x.name)===norm(r.spot_name)&&norm(x.municipality)===norm(r.municipality));if(s)return '登録済みスポットと重複の可能性';return recRows.some(x=>x.id!==r.id&&norm(x.spot_name)===norm(r.spot_name)&&norm(x.municipality)===norm(r.municipality))?'おすすめ内に同名投稿あり':''}
function renderAdminLists(){const rl=q('#recommendList'),sl=q('#adminSpotList');if(!rl||!sl)return;const term=norm(q('#adminRecSearch')?.value||'');let rows=recRows.filter(r=>!term||norm([r.spot_name,r.municipality,r.category,r.recommendation,r.nickname].join(' ')).includes(term));if(recFilter!=='all')rows=rows.filter(r=>r.status===recFilter);const counts=s=>recRows.filter(r=>r.status===s).length;if(q('#adminSummary'))q('#adminSummary').textContent=`確認待ち ${counts('pending')}件 ／ 採用済み ${counts('approved')}件 ／ 見送り ${counts('rejected')}件`;const renderRec=r=>{const dup=duplicateInfo(r);return `<div class="adminitem"><b>${safe(r.spot_name)}</b><div class="small">${safe(r.municipality)}${r.category?' · '+safe(r.category):''} · ${statusLabel(r.status)}</div>${dup?`<div class="small" style="margin-top:6px;font-weight:700">⚠ ${safe(dup)}</div>`:''}<div style="margin-top:7px;font-size:13px;line-height:1.6">${safe(r.recommendation)}</div>${r.nickname?`<div class="small">投稿者：${safe(r.nickname)}</div>`:''}${r.url?`<a href="${safe(r.url)}" target="_blank" rel="noopener noreferrer" class="small">参考URLを開く ↗</a>`:''}<div class="adminbar">${r.status==='pending'?`<button class="btn primary" onclick="adoptRecommendation('${r.id}')">採用して編集</button><button class="btn danger" onclick="setRecStatus('${r.id}','rejected')">見送り</button>`:`<button class="btn soft" onclick="setRecStatus('${r.id}','pending')">確認待ちに戻す</button>`}</div></div>`};rl.innerHTML=rows.length?rows.map(renderRec).join(''):`<div class="small">${recFilter==='rejected'?'見送りしたおすすめはありません。':'該当するおすすめはありません。'}</div>`;sl.innerHTML=spotRows.length?spotRows.map(r=>`<div class="adminitem"><b>${safe(r.name)}</b><div class="small">${safe(r.municipality)} · ${safe(r.category)} · ${r.is_published?'公開中':'下書き'}</div><div class="adminbar"><button class="btn soft" onclick="editSpot('${r.id}')">編集</button><button class="btn soft" onclick="togglePublish('${r.id}',${!r.is_published})">${r.is_published?'非公開にする':'公開する'}</button><button class="btn danger" onclick="deleteSpot('${r.id}')">削除</button></div></div>`).join(''):'<div class="small">管理画面から追加したスポットはまだありません。</div>'}
window.loadAdmin=async()=>{enhanceSpotForm();enhanceAdminUI();const rl=q('#recommendList'),sl=q('#adminSpotList');if(!rl||!sl)return;rl.innerHTML='<div class="small">読み込み中…</div>';sl.innerHTML='<div class="small">読み込み中…</div>';const [rr,ss]=await Promise.all([db.from('seiban_recommendations').select('*').order('created_at',{ascending:false}),db.from('seiban_spots').select('*').order('created_at',{ascending:false})]);if(rr.error)return rl.innerHTML='<div class="note">おすすめ一覧を読み込めません：'+safe(rr.error.message)+'</div>';if(ss.error)return sl.innerHTML='<div class="note">スポット一覧を読み込めません：'+safe(ss.error.message)+'</div>';recRows=rr.data||[];spotRows=ss.data||[];renderTabs();renderAdminLists()};

const publicForm=q('#recommendForm');if(publicForm&&!publicForm.dataset.enhancedSubmit){publicForm.dataset.enhancedSubmit='1';let lastSubmit=0;publicForm.addEventListener('submit',async e=>{e.preventDefault();e.stopImmediatePropagation();const msg=q('#recommendMsg'),btn=publicForm.querySelector('button[type="submit"]'),now=Date.now();if(btn.disabled)return;if(now-lastSubmit<15000)return msg.textContent='連続送信は少し時間をあけてください。';const f=new FormData(publicForm),name=String(f.get('spot_name')||'').trim(),recommendation=String(f.get('recommendation')||'').trim(),url=String(f.get('url')||'').trim();if(name.length<2||recommendation.length<2)return msg.textContent='スポット名とおすすめ理由をもう少し詳しく入力してください。';if(url&&!validUrl(url))return msg.textContent='参考URLの形式を確認してください。';btn.disabled=true;msg.textContent='送信中…';const {error}=await db.from('seiban_recommendations').insert({spot_name:name,municipality:String(f.get('municipality')||'').trim(),category:String(f.get('category')||'').trim()||null,recommendation,url:url||null,nickname:String(f.get('nickname')||'').trim().slice(0,80)||null,status:'pending'});btn.disabled=false;if(error)return msg.textContent='送信エラー：'+error.message;lastSubmit=Date.now();publicForm.reset();msg.textContent='ありがとう！おすすめ情報を受け付けました。';},true)}
enhanceSpotForm();setupRecovery();
})();