const SUPABASE_URL = "https://jtsllyiuwdjpoulcwvqx.supabase.co";
const SUPABASE_ANON_KEY = "sb_publishable_HpRt1_FQGdfIMZo9z7Dc9Q_7DmdJnCc";

const AREAS = [
  "姫路市",
  "宍粟市",
  "たつの市",
  "太子町",
  "上郡町",
  "相生市",
  "赤穂市"
];

const FALLBACK_SPOTS = [
  {id:"fallback-coneru",slug:"bakery-coneru",name:"bakery coneru",area:"上郡町",genre:"パン",lead:"上郡駅から徒歩3分。添加物不使用の小さなパン屋さん。",description:"上郡駅近くにある、添加物不使用にこだわるベーカリー。小麦の香りを楽しめるパンが並び、駅から歩いて立ち寄りやすい一軒です。",website_url:"https://coneru.jimdofree.com",instagram_url:"https://www.instagram.com/bakery_coneru_2018",post_url:"https://www.instagram.com/p/Dc5OnmcE5DJ/",maps_url:"https://www.google.com/maps/search/?api=1&query=bakery%20coneru%20上郡町",image_url:"coneru-1.jpg",tags:["パン屋","駅近","添加物不使用"],featured:true,published:true,sort_order:10},
  {id:"fallback-merrywidow",slug:"merry-widow",name:"MERRY WIDOW patisserie&coffee roastery",area:"上郡町",genre:"カフェ",lead:"上郡駅から徒歩6分。ケーキとコーヒーを楽しむ寄り道。",description:"ケーキや焼菓子、クロワッサンサンド、パフェ、コーヒーを楽しめる上郡の一軒。散策途中の寄り道にも。",website_url:"https://www.merrywidow.net/",instagram_url:"https://www.instagram.com/merrywidow",post_url:"https://www.instagram.com/p/DchgnKHkyAs/",maps_url:"https://www.google.com/maps/search/?api=1&query=MERRY%20WIDOW%20上郡町",image_url:"",tags:["カフェ","ケーキ","コーヒー","駅近"],featured:true,published:true,sort_order:20}
];
const state={spots:[],area:"",genre:"",query:"",tab:"discover",favorites:loadFavorites()};
const el={search:document.getElementById("search"),areas:document.getElementById("areas"),genres:document.getElementById("genres"),featured:document.getElementById("featured"),spotList:document.getElementById("spotList"),listTitle:document.getElementById("listTitle"),resultCount:document.getElementById("resultCount"),emptyState:document.getElementById("emptyState"),modal:document.getElementById("modal"),modalContent:document.getElementById("modalContent"),clearArea:document.getElementById("clearArea"),selectedAreaMessage:document.getElementById("selectedAreaMessage"),spotSection:document.getElementById("spotSection")};
function loadFavorites(){try{const v=JSON.parse(localStorage.getItem("seiban-guide-favorites")||"[]");return Array.isArray(v)?v:[]}catch{return[]}}
function saveFavorites(){localStorage.setItem("seiban-guide-favorites",JSON.stringify(state.favorites))}
function escapeHtml(value=""){return String(value).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function safeUrl(value=""){if(!value)return"";try{const u=new URL(value);if(u.protocol==="https:"||u.protocol==="http:")return u.href}catch{}return""}
function spotKey(s){return String(s.id||s.slug||s.name)} function isFavorite(s){return state.favorites.includes(spotKey(s))}
function normalizeSpot(s){return{...s,tags:Array.isArray(s.tags)?s.tags:[],featured:Boolean(s.featured),published:s.published!==false,sort_order:Number(s.sort_order||0)}}
async function loadSpots(){try{const endpoint=`${SUPABASE_URL}/rest/v1/spots?select=*&published=eq.true&order=sort_order.asc,created_at.desc`;const response=await fetch(endpoint,{headers:{apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${SUPABASE_ANON_KEY}`,Accept:"application/json"}});if(!response.ok)throw new Error(`Supabase ${response.status}`);const data=await response.json();if(!Array.isArray(data))throw new Error("Invalid Supabase response");state.spots=data.map(normalizeSpot)}catch(error){console.warn("Supabaseから取得できなかったためフォールバックを表示します。",error);state.spots=FALLBACK_SPOTS.map(normalizeSpot)}render()}
function filteredSpots(){const q=state.query.trim().toLowerCase();return state.spots.filter(s=>{if(state.tab==="favorites"&&!isFavorite(s))return false;if(state.area&&s.area!==state.area)return false;if(state.genre&&s.genre!==state.genre)return false;if(q){const h=[s.name,s.area,s.genre,s.lead,s.description,...(s.tags||[])].filter(Boolean).join(" ").toLowerCase();if(!h.includes(q))return false}return true})}
function imageMarkup(s){const image=safeUrl(s.image_url);if(image)return `<img src="${escapeHtml(image)}" alt="${escapeHtml(s.name)}" loading="lazy">`;if(s.image_url&&!s.image_url.startsWith("http")&&!s.image_url.startsWith("//"))return `<img src="${escapeHtml(s.image_url)}" alt="${escapeHtml(s.name)}" loading="lazy" onerror="this.parentElement.innerHTML='<div class=&quot;spotImagePlaceholder&quot;>PHOTO</div>'">`;return `<div class="spotImagePlaceholder">PHOTO</div>`}
function cardMarkup(s){const key=spotKey(s),fav=isFavorite(s),tags=(s.tags||[]).slice(0,4).map(t=>`<span class="spotTag">${escapeHtml(t)}</span>`).join("");return `<article class="spotCard" data-spot="${escapeHtml(key)}"><div class="spotImage">${imageMarkup(s)}<button class="favoriteButton ${fav?"active":""}" type="button" data-favorite="${escapeHtml(key)}" aria-label="お気に入り">${fav?"♥":"♡"}</button></div><div class="spotBody"><div class="spotMeta"><span>${escapeHtml(s.area||"")}</span><span>・</span><span>${escapeHtml(s.genre||"")}</span></div><h3>${escapeHtml(s.name||"")}</h3>${s.lead?`<p>${escapeHtml(s.lead)}</p>`:""}${tags?`<div class="spotTags">${tags}</div>`:""}<button class="cardOpen" type="button" data-open="${escapeHtml(key)}">この場所を見る</button></div></article>`}
function renderFeatured(){if(!el.featured)return;if(state.tab==="favorites"){el.featured.closest("section")?.classList.add("hidden");return}el.featured.closest("section")?.classList.remove("hidden");const spots=state.spots.filter(s=>s.featured).slice(0,4);if(!spots.length){el.featured.innerHTML="";el.featured.closest("section")?.classList.add("hidden");return}el.featured.innerHTML=spots.map(cardMarkup).join("")}
function renderList(){const spots=filteredSpots();el.listTitle.textContent=state.tab==="favorites"?"お気に入り":state.area?`${state.area}のおすすめ`:"おすすめスポット";el.resultCount.textContent=`${spots.length}件`;if(!spots.length){el.spotList.innerHTML="";el.emptyState.classList.remove("hidden");el.emptyState.innerHTML=state.tab==="favorites"?`<strong>お気に入りはまだありません。</strong><p>気になる場所の♡をタップしてね。</p>`:`<strong>まだスポットがありません。</strong><p>条件を変えて探してみてね。</p>`;return}el.emptyState.classList.add("hidden");el.spotList.innerHTML=spots.map(cardMarkup).join("")}
function updateAreaUI(){document.querySelectorAll("[data-area]").forEach(b=>b.classList.toggle("active",(b.dataset.area||"")===state.area));if(el.selectedAreaMessage)el.selectedAreaMessage.textContent=state.area?`${state.area}を表示中`:"すべてのエリアを表示中"}
function updateGenreUI(){document.querySelectorAll("[data-genre]").forEach(b=>b.classList.toggle("active",(b.dataset.genre||"")===state.genre))} function updateTabUI(){document.querySelectorAll("[data-tab]").forEach(b=>b.classList.toggle("active",b.dataset.tab===state.tab))}
function render(){updateAreaUI();updateGenreUI();updateTabUI();renderFeatured();renderList()}
function chooseArea(area){state.area=area||"";state.tab="discover";render();setTimeout(()=>el.spotSection?.scrollIntoView({behavior:"smooth",block:"start"}),80)}
function toggleFavorite(key){state.favorites=state.favorites.includes(key)?state.favorites.filter(i=>i!==key):[...state.favorites,key];saveFavorites();render()}
function findSpot(key){return state.spots.find(s=>spotKey(s)===String(key))}
function modalImageMarkup(s){const image=safeUrl(s.image_url);if(image)return `<div class="modalHero"><img src="${escapeHtml(image)}" alt="${escapeHtml(s.name)}"></div>`;if(s.image_url&&!s.image_url.startsWith("http")&&!s.image_url.startsWith("//"))return `<div class="modalHero"><img src="${escapeHtml(s.image_url)}" alt="${escapeHtml(s.name)}"></div>`;return""}
function openSpot(key){const s=findSpot(key);if(!s)return;const links=[{label:"Google Mapsで見る",url:safeUrl(s.maps_url)||`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${s.name} ${s.area}`)}`,primary:true},{label:"公式サイト",url:safeUrl(s.website_url)},{label:"Instagram",url:safeUrl(s.instagram_url)},{label:"紹介投稿を見る",url:safeUrl(s.post_url)}].filter(l=>l.url);el.modalContent.innerHTML=`<div class="modalContent">${modalImageMarkup(s)}<div class="spotMeta"><span>${escapeHtml(s.area||"")}</span><span>・</span><span>${escapeHtml(s.genre||"")}</span></div><h2>${escapeHtml(s.name||"")}</h2>${s.lead?`<p><strong>${escapeHtml(s.lead)}</strong></p>`:""}${s.description?`<p>${escapeHtml(s.description)}</p>`:""}${s.address?`<p>〒 ${escapeHtml(s.address)}</p>`:""}${(s.tags||[]).length?`<div class="spotTags">${s.tags.map(t=>`<span class="spotTag">${escapeHtml(t)}</span>`).join("")}</div>`:""}<div class="modalLinks">${links.map(l=>`<a href="${escapeHtml(l.url)}" target="_blank" rel="noopener noreferrer" class="${l.primary?"primary":""}">${escapeHtml(l.label)}</a>`).join("")}</div></div>`;el.modal.classList.remove("hidden");document.body.style.overflow="hidden"}
function closeModal(){el.modal.classList.add("hidden");document.body.style.overflow=""}
document.addEventListener("click",event=>{const a=event.target.closest("[data-area]");if(a){chooseArea(a.dataset.area||"");return}const g=event.target.closest("[data-genre]");if(g){state.genre=g.dataset.genre||"";state.tab="discover";render();return}const f=event.target.closest("[data-favorite]");if(f){toggleFavorite(f.dataset.favorite);return}const o=event.target.closest("[data-open]");if(o){openSpot(o.dataset.open);return}const t=event.target.closest("[data-tab]");if(t){state.tab=t.dataset.tab;if(state.tab==="favorites"){state.area="";state.genre=""}render();el.spotSection?.scrollIntoView({behavior:"smooth",block:"start"});return}if(event.target.closest("[data-close-modal]"))closeModal()});
el.search?.addEventListener("input",e=>{state.query=e.target.value||"";state.tab="discover";render()});el.clearArea?.addEventListener("click",()=>{state.area="";render()});document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});if("serviceWorker" in navigator){window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}))}loadSpots();