const SUPABASE_URL='https://jtsllyiuwdjpoulcwvqx.supabase.co';
const SUPABASE_KEY='sb_publishable_UpaM7WHRbU2R6oZk09OpUA_QWcEceKc';
const AREAS=['姫路市','宍粟市','たつの市','太子町','上郡町','相生市','赤穂市'];
const FALLBACK=[
{id:'coneru',slug:'bakery-coneru',area:'上郡町',name:'bakery coneru',genre:'パン',lead:'上郡駅から徒歩3分。添加物不使用の小さなパン屋さん。',description:'上郡駅近くにある、添加物不使用にこだわるベーカリー。',tags:['パン屋','駅近','添加物不使用'],featured:true,website_url:'https://coneru.jimdofree.com',instagram_url:'https://www.instagram.com/bakery_coneru_2018'},
{id:'merry',slug:'merry-widow',area:'上郡町',name:'MERRY WIDOW patisserie&coffee roastery',genre:'カフェ',lead:'上郡駅から徒歩6分。ケーキとコーヒーを楽しむ寄り道。',description:'ケーキや焼菓子、クロワッサンサンド、パフェ、コーヒーを楽しめる上郡の一軒。',tags:['カフェ','ケーキ','コーヒー','駅近'],featured:true,website_url:'https://www.merrywidow.net/',instagram_url:'https://www.instagram.com/merrywidow'}];
let SPOTS=[];let state={area:null,genre:'すべて',q:'',tab:'discover',saved:new Set(JSON.parse(localStorage.getItem('seibanSaved')||'[]'))};
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function save(){localStorage.setItem('seibanSaved',JSON.stringify([...state.saved]))}
function maps(s){return s.maps_url||`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(s.name+' '+s.area)}`}
function visual(s){return s.image_url?`<img src="${esc(s.image_url)}" alt="${esc(s.name)}" loading="lazy">`:`<span>${s.genre==='パン'?'🥐':s.genre==='カフェ'?'☕':'📍'}</span>`}
function card(s,featured=false){return `<article class="${featured?'featureCard':'spotCard'}" data-open="${s.slug}">${featured?'':`<button class="saveBtn ${state.saved.has(s.slug)?'saved':''}" data-save="${s.slug}" aria-label="保存">${state.saved.has(s.slug)?'♥':'♡'}</button>`}<div class="visual">${visual(s)}</div><div class="cardBody"><div class="meta">${esc(s.area)} · ${esc(s.genre)}</div><b>${esc(s.name)}</b><p>${esc(s.lead)}</p></div></article>`}
function genres(){return ['すべて',...new Set(SPOTS.map(s=>s.genre))]}
function filtered(){let x=SPOTS.filter(s=>(!state.area||s.area===state.area)&&(state.genre==='すべて'||s.genre===state.genre));if(state.q){let q=state.q.toLowerCase();x=x.filter(s=>[s.name,s.area,s.genre,s.lead,...(s.tags||[])].join(' ').toLowerCase().includes(q))}if(state.tab==='saved')x=x.filter(s=>state.saved.has(s.slug));return x}
function render(){let featured=SPOTS.filter(s=>s.featured);$('#featured').innerHTML=featured.length?featured.map(s=>card(s,true)).join(''):'<div class="emptyMini">おすすめを準備中です。</div>';$('#areas').innerHTML=AREAS.map(a=>`<button class="areaBtn ${state.area===a?'active':''}" data-area="${a}"><span class="pin">⌖</span>${a}</button>`).join('');$('#genres').innerHTML=genres().map(g=>`<button class="chip ${state.genre===g?'active':''}" data-genre="${esc(g)}">${esc(g)}</button>`).join('');let list=filtered();$('#spotGrid').innerHTML=list.map(s=>card(s)).join('');$('#count').textContent=`${list.length} SPOTS`;$('#empty').classList.toggle('hidden',list.length>0);$('#listTitle').textContent=state.tab==='saved'?'保存したスポット':'おすすめスポット';document.querySelectorAll('.bottom button').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.tab))}
function openSpot(slug){let s=SPOTS.find(x=>x.slug===slug);if(!s)return;$('#modalVisual').innerHTML=visual(s);$('#modalMeta').textContent=`${s.area} · ${s.genre}`;$('#modalName').textContent=s.name;$('#modalLead').textContent=s.lead;$('#modalDesc').textContent=s.description||'';$('#modalTags').innerHTML=(s.tags||[]).map(t=>`<span class="tag"># ${esc(t)}</span>`).join('');let links=`<a class="primary" href="${maps(s)}" target="_blank" rel="noopener">Google Mapsで見る</a>`;if(s.post_url)links+=`<a class="secondary" href="${esc(s.post_url)}" target="_blank" rel="noopener">紹介投稿を見る</a>`;if(s.instagram_url)links+=`<a class="secondary" href="${esc(s.instagram_url)}" target="_blank" rel="noopener">Instagram</a>`;if(s.website_url)links+=`<a class="secondary" href="${esc(s.website_url)}" target="_blank" rel="noopener">公式サイト</a>`;links+=`<button class="secondary" data-modal-save="${s.slug}">${state.saved.has(s.slug)?'♥ 保存済み':'♡ 気になるに保存'}</button>`;$('#modalActions').innerHTML=links;$('#modal').classList.remove('hidden');document.body.style.overflow='hidden'}
async function loadSpots(){try{const r=await fetch(`${SUPABASE_URL}/rest/v1/spots?select=*&published=eq.true&order=sort_order.asc,created_at.asc`,{headers:{apikey:SUPABASE_KEY}});if(!r.ok)throw new Error(await r.text());SPOTS=await r.json();if(!SPOTS.length)SPOTS=FALLBACK}catch(e){console.error('Supabase load failed',e);SPOTS=FALLBACK;$('#dataStatus').textContent='オフラインデータを表示中'}render()}
document.addEventListener('click',e=>{let x=e.target.closest('[data-save]');if(x){e.stopPropagation();let id=x.dataset.save;state.saved.has(id)?state.saved.delete(id):state.saved.add(id);save();render();return}let ms=e.target.closest('[data-modal-save]');if(ms){let id=ms.dataset.modalSave;state.saved.has(id)?state.saved.delete(id):state.saved.add(id);save();openSpot(id);render();return}let o=e.target.closest('[data-open]');if(o)openSpot(o.dataset.open);let a=e.target.closest('[data-area]');if(a){state.area=state.area===a.dataset.area?null:a.dataset.area;render()}let g=e.target.closest('[data-genre]');if(g){state.genre=g.dataset.genre;render()}let tab=e.target.closest('[data-tab]');if(tab){state.tab=tab.dataset.tab;render();window.scrollTo({top:0,behavior:'smooth'})}if(e.target.closest('[data-close]')){$('#modal').classList.add('hidden');document.body.style.overflow=''}});
$('#search').addEventListener('input',e=>{state.q=e.target.value.trim();render()});$('#clearSearch').onclick=()=>{$('#search').value='';state.q='';render()};$('#allArea').onclick=()=>{state.area=null;render()};
loadSpots();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
