(()=>{
'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let spots=[], recs=[], filter='pending', editId=null, recId=null;
async function isAdmin(){const {data:s}=await db.auth.getSession();if(!s.session)return false;const {data,error}=await db.rpc('is_seiban_admin');return !error&&data===true}
function f(){return $('#spotForm')} function put(n,v){const x=f()?.elements?.namedItem(n);if(x)x.value=v??''}
function prepareForm(){const x=f();if(!x)return;if(!x.elements.namedItem('image_urls')){const t=document.createElement('textarea');t.name='image_urls';t.placeholder='画像URL（複数は改行）';x.querySelector('[name="map_url"]')?.after(t)}let b=$('#cancelSpotEdit');if(!b){b=document.createElement('button');b.type='button';b.id='cancelSpotEdit';b.className='btn soft hidden';b.textContent='編集をキャンセル';x.querySelector('button[type="submit"]')?.after(b);b.onclick=reset}x.onsubmit=save}
function reset(){const x=f();if(!x)return;x.reset();const c=x.elements.namedItem('is_published');if(c)c.checked=true;editId=recId=null;$('#cancelSpotEdit')?.classList.add('hidden');const b=x.querySelector('button[type="submit"]');if(b)b.textContent='スポットを登録'}
window.editSpotV3=id=>{prepareForm();const r=spots.find(x=>String(x.id)===String(id));if(!r)return alert('対象が見つかりません');editId=r.id;recId=null;['name','municipality','category','description','website_url','instagram_url','post_url','map_url'].forEach(k=>put(k,r[k]));put('image_urls',(r.image_urls||[]).join('\n'));const c=f().elements.namedItem('is_published');if(c)c.checked=!!r.is_published;const b=f().querySelector('button[type="submit"]');if(b)b.textContent='変更を保存';$('#cancelSpotEdit')?.classList.remove('hidden');$('#spotMsg').textContent='編集中：'+r.name;f().scrollIntoView({behavior:'smooth',block:'start'})};
window.adoptV3=id=>{prepareForm();const r=recs.find(x=>String(x.id)===String(id));if(!r)return;editId=null;recId=r.id;put('name',r.spot_name);put('municipality',r.municipality);put('category',r.category||'その他');put('description',r.recommendation);if(r.url){if(/instagram\.com/i.test(r.url))put('instagram_url',r.url);else put('website_url',r.url)}const c=f().elements.namedItem('is_published');if(c)c.checked=false;$('#cancelSpotEdit')?.classList.remove('hidden');$('#spotMsg').textContent='おすすめ内容を編集して登録できます。';f().scrollIntoView({behavior:'smooth',block:'start'})};
async function save(e){e.preventDefault();if(!await isAdmin())return alert('管理者としてログインしてください');const x=f(),d=new FormData(x),images=String(d.get('image_urls')||'').split(/\n|,/).map(s=>s.trim()).filter(Boolean),payload={name:String(d.get('name')||'').trim(),municipality:String(d.get('municipality')||'').trim(),category:String(d.get('category')||'その他').trim(),description:String(d.get('description')||'').trim(),website_url:String(d.get('website_url')||'').trim()||null,instagram_url:String(d.get('instagram_url')||'').trim()||null,post_url:String(d.get('post_url')||'').trim()||null,map_url:String(d.get('map_url')||'').trim()||null,image_urls:images,is_published:d.get('is_published')==='on'};if(!payload.name||!payload.municipality)return $('#spotMsg').textContent='スポット名と市町村は必須です。';let res;if(editId){res=await db.rpc('seiban_v3_update_spot',{p_id:+editId,p_payload:payload})}else{res=await db.rpc('seiban_v3_insert_spot',{p_payload:payload})}if(res.error||res.data!==true){console.error(res.error);return $('#spotMsg').textContent='保存できませんでした：'+(res.error?.message||'更新失敗')}if(recId)await db.rpc('seiban_v2_set_recommendation',{p_id:+recId,p_value:'approved'});reset();$('#spotMsg').textContent='保存しました。';if(typeof loadRemoteSpots==='function')await loadRemoteSpots();await window.loadAdmin()}
window.pubV3=async(id,val)=>{if(!val&&!confirm('非公開にしますか？'))return;const {data,error}=await db.rpc('seiban_v2_set_published',{p_id:+id,p_value:!!val});if(error||data!==true)return alert('変更できませんでした');if(typeof loadRemoteSpots==='function')await loadRemoteSpots();await window.loadAdmin()};
window.delV3=async id=>{if(!confirm('完全に削除しますか？'))return;const {data,error}=await db.rpc('seiban_v2_delete_spot',{p_id:+id});if(error||data!==true)return alert('削除できませんでした');if(typeof loadRemoteSpots==='function')await loadRemoteSpots();await window.loadAdmin()};
window.recV3=async(id,status)=>{const {data,error}=await db.rpc('seiban_v2_set_recommendation',{p_id:+id,p_value:status});if(error||data!==true)return alert('更新できませんでした');await window.loadAdmin()};
function render(){const rl=$('#recommendList'),sl=$('#adminSpotList');if(rl){const count=s=>recs.filter(r=>r.status===s).length;const tabs=`<div class="adminbar">${[['pending','確認待ち '+count('pending')],['approved','採用済み '+count('approved')],['rejected','見送り '+count('rejected')],['all','すべて '+recs.length]].map(([v,l])=>`<button type="button" class="btn ${filter===v?'primary':'soft'}" data-filter="${v}">${l}</button>`).join('')}</div>`;const a=filter==='all'?recs:recs.filter(r=>r.status===filter);rl.innerHTML=tabs+(a.map(r=>`<div class="adminitem"><b>${esc(r.spot_name)}</b><div class="small">${esc(r.municipality)} · ${esc(r.status)}</div><div style="margin-top:7px;font-size:13px">${esc(r.recommendation)}</div><div class="adminbar">${r.status!=='approved'?`<button type="button" class="btn primary" onclick="adoptV3('${r.id}')">採用して編集</button>`:''}${r.status!=='rejected'?`<button type="button" class="btn danger" onclick="recV3('${r.id}','rejected')">見送り</button>`:`<button type="button" class="btn soft" onclick="recV3('${r.id}','pending')">確認待ちへ戻す</button>`}</div></div>`).join('')||'<div class="small">該当なし</div>');rl.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render()})}if(sl)sl.innerHTML=spots.map(r=>`<div class="adminitem"><b>${esc(r.name)}</b><div class="small">${esc(r.municipality)} · ${r.is_published?'公開中':'非公開'}</div><div class="adminbar"><button type="button" class="btn soft" onclick="editSpotV3('${r.id}')">編集</button><button type="button" class="btn soft" onclick="pubV3('${r.id}',${!r.is_published})">${r.is_published?'非公開にする':'公開する'}</button><button type="button" class="btn danger" onclick="delV3('${r.id}')">削除</button></div></div>`).join('')||'<div class="small">登録スポットなし</div>'}
window.loadAdmin=async()=>{if(!await isAdmin())return;prepareForm();const [a,b]=await Promise.all([db.from('seiban_recommendations').select('*').order('created_at',{ascending:false}),db.from('seiban_spots').select('*').order('created_at',{ascending:false})]);if(a.error||b.error)return alert('管理データを読み込めませんでした');recs=a.data||[];spots=b.data||[];render()};
window.checkAdmin=async()=>{const {data:s}=await db.auth.getSession(),ok=await isAdmin();$('#adminLogin')?.classList.toggle('hidden',!!s.session&&ok);$('#adminPanel')?.classList.toggle('hidden',!ok);if(ok)await window.loadAdmin()};
prepareForm();
})();