(()=>{
'use strict';
const $=s=>document.querySelector(s);
const esc2=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let recFilter='pending';
async function adminSession(){const {data}=await db.auth.getSession();return data.session||null}
async function ensureAdmin(){const s=await adminSession();if(!s)return false;const {data,error}=await db.rpc('is_seiban_admin');return !error&&data===true}
window.checkAdmin=async()=>{const s=await adminSession();const ok=await ensureAdmin();$('#adminLogin')?.classList.toggle('hidden',!!s&&ok);$('#adminPanel')?.classList.toggle('hidden',!ok);if(s&&!ok){const m=$('#loginMsg');if(m)m.textContent='このアカウントには管理者権限がありません。'}if(ok)await window.loadAdmin()};
window.loadAdmin=async()=>{if(!await ensureAdmin())return;const rl=$('#recommendList'),sl=$('#adminSpotList');if(rl)rl.innerHTML='<div class="small">読み込み中…</div>';if(sl)sl.innerHTML='<div class="small">読み込み中…</div>';const [rr,ss]=await Promise.all([db.from('seiban_recommendations').select('*').order('created_at',{ascending:false}),db.from('seiban_spots').select('*').order('created_at',{ascending:false})]);
if(rl){if(rr.error)rl.innerHTML='<div class="note">おすすめを読み込めませんでした。</div>';else{const rows=rr.data||[];const counts={pending:0,approved:0,rejected:0};rows.forEach(x=>counts[x.status]=(counts[x.status]||0)+1);const tabs=`<div class="adminbar"><button class="btn ${recFilter==='pending'?'primary':'soft'}" data-rf="pending">確認待ち ${counts.pending}</button><button class="btn ${recFilter==='approved'?'primary':'soft'}" data-rf="approved">採用済み ${counts.approved}</button><button class="btn ${recFilter==='rejected'?'primary':'soft'}" data-rf="rejected">見送り ${counts.rejected}</button><button class="btn ${recFilter==='all'?'primary':'soft'}" data-rf="all">すべて ${rows.length}</button></div>`;const shown=recFilter==='all'?rows:rows.filter(x=>x.status===recFilter);rl.innerHTML=tabs+(shown.length?shown.map(r=>`<div class="adminitem"><b>${esc2(r.spot_name)}</b><div class="small">${esc2(r.municipality)}${r.category?' · '+esc2(r.category):''} · ${esc2(r.status)}</div><div style="margin-top:7px;font-size:13px;line-height:1.6">${esc2(r.recommendation)}</div>${r.url?`<a href="${esc2(r.url)}" target="_blank" rel="noopener" class="small">URLを開く ↗</a>`:''}<div class="adminbar">${r.status!=='approved'?`<button class="btn primary" data-adopt="${r.id}">採用して編集</button>`:''}${r.status!=='rejected'?`<button class="btn danger" data-reject="${r.id}">見送り</button>`:`<button class="btn soft" data-pending="${r.id}">確認待ちへ戻す</button>`}</div></div>`).join(''):'<div class="small">該当するおすすめはありません。</div>');rl.querySelectorAll('[data-rf]').forEach(b=>b.onclick=()=>{recFilter=b.dataset.rf;window.loadAdmin()});rl.querySelectorAll('[data-reject]').forEach(b=>b.onclick=()=>window.setRecStatus(+b.dataset.reject,'rejected'));rl.querySelectorAll('[data-pending]').forEach(b=>b.onclick=()=>window.setRecStatus(+b.dataset.pending,'pending'));rl.querySelectorAll('[data-adopt]').forEach(b=>b.onclick=()=>adopt(+b.dataset.adopt,rows));}}
if(sl){if(ss.error)sl.innerHTML='<div class="note">スポットを読み込めませんでした。</div>';else sl.innerHTML=(ss.data||[]).map(r=>`<div class="adminitem"><b>${esc2(r.name)}</b><div class="small">${esc2(r.municipality)} · ${esc2(r.category)} · ${r.is_published?'公開中':'非公開'}</div><div class="adminbar"><button class="btn soft" data-edit="${r.id}">編集</button><button class="btn soft" data-pub="${r.id}" data-val="${!r.is_published}">${r.is_published?'非公開にする':'公開する'}</button><button class="btn danger" data-del="${r.id}">削除</button></div></div>`).join('')||'<div class="small">登録スポットはありません。</div>';sl.querySelectorAll('[data-pub]').forEach(b=>b.onclick=()=>window.togglePublish(+b.dataset.pub,b.dataset.val==='true'));sl.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>window.deleteSpot(+b.dataset.del));sl.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editSpot(+b.dataset.edit,ss.data||[]));}}
};
window.setRecStatus=async(id,status)=>{const {data,error}=await db.rpc('seiban_v2_set_recommendation',{p_id:id,p_value:status});if(error||data!==true){alert('更新できませんでした。');return}await window.loadAdmin()};
window.togglePublish=async(id,val)=>{if(!confirm(val?'このスポットを公開しますか？':'このスポットを非公開にしますか？'))return;const {data,error}=await db.rpc('seiban_v2_set_published',{p_id:id,p_value:val});if(error||data!==true){alert('公開状態を変更できませんでした。');return}await loadRemoteSpots();await window.loadAdmin()};
window.deleteSpot=async id=>{if(!confirm('このスポットを完全に削除しますか？'))return;const {data,error}=await db.rpc('seiban_v2_delete_spot',{p_id:id});if(error||data!==true){alert('削除できませんでした。');return}await loadRemoteSpots();await window.loadAdmin()};
function form(){return $('#spotForm')}
function setField(n,v){const e=form()?.elements?.namedItem(n);if(e)e.value=v??''}
function adopt(id,rows){const r=rows.find(x=>x.id===id);if(!r)return;form().dataset.recommendationId=id;delete form().dataset.spotId;setField('name',r.spot_name);setField('municipality',r.municipality);setField('category',r.category||'その他');setField('description',r.recommendation);setField('website_url',r.url||'');$('#spotMsg').textContent='内容を確認・編集して「スポットを登録」を押してください。';form().scrollIntoView({behavior:'smooth',block:'start'})}
function editSpot(id,rows){const r=rows.find(x=>x.id===id);if(!r)return;form().dataset.spotId=id;delete form().dataset.recommendationId;['name','municipality','category','description','website_url','instagram_url','post_url','map_url'].forEach(n=>setField(n,r[n==='website_url'?'website_url':n]||''));const c=form().elements.namedItem('is_published');if(c)c.checked=!!r.is_published;$('#spotMsg').textContent='編集中です。保存すると上書きされます。';form().scrollIntoView({behavior:'smooth',block:'start'})}
const oldSpot=form();if(oldSpot){oldSpot.onsubmit=async e=>{e.preventDefault();if(!await ensureAdmin())return alert('管理者としてログインしてください。');const f=new FormData(oldSpot),payload={name:String(f.get('name')||'').trim(),municipality:String(f.get('municipality')||''),category:String(f.get('category')||'その他').trim(),description:String(f.get('description')||'').trim(),website_url:String(f.get('website_url')||'').trim()||null,instagram_url:String(f.get('instagram_url')||'').trim()||null,post_url:String(f.get('post_url')||'').trim()||null,map_url:String(f.get('map_url')||'').trim()||null,is_published:f.get('is_published')==='on'};const id=oldSpot.dataset.spotId;const q=id?db.from('seiban_spots').update({...payload,updated_at:new Date().toISOString()}).eq('id',+id):db.from('seiban_spots').insert(payload);const {error}=await q;if(error){$('#spotMsg').textContent='保存できませんでした。';return}const rid=oldSpot.dataset.recommendationId;if(rid)await db.rpc('seiban_v2_set_recommendation',{p_id:+rid,p_value:'approved'});oldSpot.reset();oldSpot.elements.namedItem('is_published').checked=true;delete oldSpot.dataset.spotId;delete oldSpot.dataset.recommendationId;$('#spotMsg').textContent='保存しました。';await loadRemoteSpots();await window.loadAdmin()}}
const rf=$('#recommendForm');if(rf){rf.onsubmit=async e=>{e.preventDefault();const f=new FormData(rf),msg=$('#recommendMsg');msg.textContent='送信中…';const payload={spot_name:String(f.get('spot_name')||'').trim(),municipality:String(f.get('municipality')||''),category:String(f.get('category')||'').trim()||null,recommendation:String(f.get('recommendation')||'').trim(),url:String(f.get('url')||'').trim()||null,nickname:String(f.get('nickname')||'').trim()||null,status:'pending'};const {error}=await db.from('seiban_recommendations').insert(payload);if(error){msg.textContent='送信できませんでした。';return}rf.reset();msg.textContent='送信しました。管理者が確認してから掲載します。'}}
window.addEventListener('pageshow',()=>{const a=$('#admin');if(a?.classList.contains('active'))window.checkAdmin()});
})();